# Muhammad Naveed
# PIAIC58491

In [2]:
#Any 50 Methods or attributes implementions

In [3]:
import numpy as np

In [4]:
a=np.arange(6).reshape(3,2)
#creating an array of 6 elements with 3 rows 2 columns

In [5]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
a.ndim
#its describing the dimensions of the array a

2

In [7]:
#data type of array a
a.dtype.name

'int32'

In [8]:
# item size of in bits 
a.itemsize

4

In [9]:
#size of array
a.size

6

In [10]:
#can't resize the array create by the method of arrange
a.resize(4)
print(a)

ValueError: cannot resize this array: it does not own its data

In [11]:
#Resizing array defined 
array=np.array([1,2,3,4,5,6,7,8,9,10])
array.resize(6)
print(array)

[1 2 3 4 5 6]


In [12]:
array.resize(2,2)
print(array)

[[1 2]
 [3 4]]


In [13]:
#above we are creating 2D as array 
#if we have to create 1D or 3D arrays then there are following ways to create
oneD=np.arange(5)
twoD=np.arange(8).reshape(2,4)
threeD=np.arange(12).reshape(2,3,2)

In [14]:
oneD

array([0, 1, 2, 3, 4])

In [15]:
twoD

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
threeD

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [17]:
type(threeD)

numpy.ndarray

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((2,3,4), dtype=np.int16)
#data type can be defined while initializing the array

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [20]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
#let's try matrix product on arrays and simple elementwise products on arrays

A=np.array([[2,2],
            [3,1]])

B=np.array([[1,1],
            [0,1]])


In [22]:
A*B        #Elementwise simple product of arrays

array([[2, 2],
       [0, 1]])

In [23]:
A@B         #matrix product of arrays

array([[2, 4],
       [3, 4]])

In [24]:
A.dot(B)    #another way of finding matrix product

array([[2, 4],
       [3, 4]])

In [25]:
#concatenate the arrays we have defined above A and B
arr=np.concatenate((A,B))
print (arr)

[[2 2]
 [3 1]
 [1 1]
 [0 1]]


In [26]:
#Finf shape of an array
arr.shape

(4, 2)

In [27]:
#change the shape of array
arr=arr.reshape(8,1)
print(arr)

[[2]
 [2]
 [3]
 [1]
 [1]
 [1]
 [0]
 [1]]


In [33]:
nmbr=np.random.rand(2,3)
print(nmbr)

[[0.77980949 0.41761482 0.44678224]
 [0.34396678 0.50305363 0.95512606]]
